#!/usr/bin/env node

var name = process.argv[2],
    ownership = require('./'),
    path = require('path'),
    users = require('./example-users.json');

if (!name) throw new Error('usage: ' + path.basename(process.argv[1]) + ' packagename');

console.log('adding ' + users.length + ' owners to ' + name);

ownership.addUsersToPackage(users, [name], function(err) {
});
